import {
  CompanyCategory,
  CompanyRemotePolicy,
  EmploymentType,
  ExperienceLevel,
  WorkplaceType,
} from "@prisma/client";
import { prisma } from "../lib/db";

type SeedContact = {
  name: string;
  title?: string;
  team?: string;
  notes?: string;
};

type SeedCompany = {
  name: string;
  slug: string;
  websiteUrl?: string;
  careersUrl?: string;
  headquarters?: string;
  hiringRegions: string[];
  locations: string[];
  remotePolicy: CompanyRemotePolicy;
  companyCategory: CompanyCategory;
  companySize?: string;
  foundedYear?: number;
  stackTags: string[];
  gameTags: string[];
  roleFocusTags: string[];
  industryTags: string[];
  hiringSignals: string[];
  atsProviders: string[];
  emailPatterns: string[];
  coldCallPhone?: string;
  notes?: string;
  outreachTips?: string;
  linkedinUrl?: string;
  activeHiring: boolean;
  contacts: SeedContact[];
};

function c(input: SeedCompany) {
  return {
    ...input,
    hiringRegions: JSON.stringify(input.hiringRegions),
    locations: JSON.stringify(input.locations),
    stackTags: JSON.stringify(input.stackTags),
    gameTags: JSON.stringify(input.gameTags),
    roleFocusTags: JSON.stringify(input.roleFocusTags),
    industryTags: JSON.stringify(input.industryTags),
    hiringSignals: JSON.stringify(input.hiringSignals),
    atsProviders: JSON.stringify(input.atsProviders),
    emailPatterns: JSON.stringify(input.emailPatterns),
  };
}

const companies = [
  c({
    name: "Epic Games",
    slug: "epic-games",
    websiteUrl: "https://www.epicgames.com",
    careersUrl: "https://www.epicgames.com/site/en-US/careers/jobs",
    headquarters: "Cary, NC",
    hiringRegions: ["US", "Remote US"],
    locations: ["Cary, NC", "Bellevue, WA", "Remote US"],
    remotePolicy: CompanyRemotePolicy.FLEXIBLE,
    companyCategory: CompanyCategory.GAMING,
    companySize: "5000+",
    foundedYear: 1991,
    stackTags: ["C++", "Unreal Engine", "Backend", "Tools"],
    gameTags: ["Engine", "Gameplay", "Online Services"],
    roleFocusTags: ["Engine programmer", "Gameplay programmer", "Tools engineer"],
    industryTags: ["Game development", "Engine technology"],
    hiringSignals: ["Large multi-team org", "Internships", "New grad pipelines"],
    atsProviders: ["Greenhouse"],
    emailPatterns: ["first.last@epicgames.com"],
    notes: "North Carolina anchor target for engine, gameplay, tools, and platform roles.",
    outreachTips: "Mention gameplay systems, responsive movement work, custom tools, or engine-side optimization experience.",
    linkedinUrl: "https://www.linkedin.com/company/epic-games/",
    activeHiring: true,
    contacts: [{ name: "Recruiting Team", title: "Talent Acquisition", team: "Engineering", notes: "Look for engineering recruiters and gameplay managers in Cary." }],
  }),
  c({
    name: "Insomniac Games",
    slug: "insomniac-games",
    websiteUrl: "https://insomniac.games",
    careersUrl: "https://insomniac.games/careers/",
    headquarters: "Burbank, CA",
    hiringRegions: ["US"],
    locations: ["Burbank, CA", "Durham, NC"],
    remotePolicy: CompanyRemotePolicy.HYBRID,
    companyCategory: CompanyCategory.GAMING,
    companySize: "500-1000",
    foundedYear: 1994,
    stackTags: ["C++", "Gameplay systems", "Tools"],
    gameTags: ["Action games", "Gameplay", "Animation systems"],
    roleFocusTags: ["Gameplay programmer", "Tools engineer"],
    industryTags: ["Console games"],
    hiringSignals: ["Gameplay teams", "Animation-heavy production"],
    atsProviders: ["Workday/Other"],
    emailPatterns: [],
    notes: "High fit for gameplay, combat feel, and systems work. Durham presence helps geographically.",
    outreachTips: "Use concrete examples of player movement, combat feel, enemy AI, and polish work.",
    linkedinUrl: "https://www.linkedin.com/company/insomniac-games/",
    activeHiring: true,
    contacts: [{ name: "Engineering Recruiter", title: "Talent Acquisition", notes: "Use Durham and gameplay keywords in your outreach search." }],
  }),
  c({
    name: "Methodical Games",
    slug: "methodical-games",
    websiteUrl: "https://www.methodicalgames.com",
    careersUrl: "https://www.methodicalgames.com/careers",
    headquarters: "Raleigh, NC",
    hiringRegions: ["US"],
    locations: ["Raleigh, NC"],
    remotePolicy: CompanyRemotePolicy.HYBRID,
    companyCategory: CompanyCategory.GAMING,
    companySize: "1-50",
    foundedYear: 2022,
    stackTags: ["Unity", "C#", "Gameplay"],
    gameTags: ["Indie studio", "Action games"],
    roleFocusTags: ["Gameplay programmer", "Generalist programmer"],
    industryTags: ["Game development"],
    hiringSignals: ["Smaller team", "Generalist-friendly"],
    atsProviders: ["Direct careers page"],
    emailPatterns: [],
    notes: "Local North Carolina studio worth tracking for networking and informational chats.",
    outreachTips: "Lead with shipped prototypes, initiative, and willingness to work across systems and polish.",
    linkedinUrl: "https://www.linkedin.com/company/methodical-games/",
    activeHiring: true,
    contacts: [{ name: "Richard Baker", title: "Principal Software Engineer", notes: "Use a short networking note and ask about team needs rather than directly asking for a job." }],
  }),
  c({
    name: "Ubisoft Red Storm",
    slug: "ubisoft-red-storm",
    websiteUrl: "https://www.ubisoft.com",
    careersUrl: "https://www.ubisoft.com/en-us/company/careers",
    headquarters: "Morrisville, NC",
    hiringRegions: ["US"],
    locations: ["Morrisville, NC"],
    remotePolicy: CompanyRemotePolicy.HYBRID,
    companyCategory: CompanyCategory.GAMING,
    companySize: "200-500",
    foundedYear: 1996,
    stackTags: ["C++", "Gameplay", "Multiplayer"],
    gameTags: ["Shooter games", "VR"],
    roleFocusTags: ["Gameplay engineer", "Online engineer"],
    industryTags: ["Game development"],
    hiringSignals: ["Established studio", "Technical design and online gameplay work"],
    atsProviders: ["Workday/Other"],
    emailPatterns: [],
    notes: "Strong NC studio target for gameplay, systems, and online features.",
    outreachTips: "Talk about player feel, combat logic, movement systems, and clean implementation.",
    linkedinUrl: "https://www.linkedin.com/company/ubisoft/",
    activeHiring: true,
    contacts: [{ name: "Studio Recruiting", title: "Talent Acquisition", notes: "Search Ubisoft recruiter plus Red Storm or Morrisville." }],
  }),
  c({
    name: "Red Hat",
    slug: "red-hat",
    websiteUrl: "https://www.redhat.com",
    careersUrl: "https://www.redhat.com/en/jobs",
    headquarters: "Raleigh, NC",
    hiringRegions: ["US", "Remote select"],
    locations: ["Raleigh, NC", "Remote US"],
    remotePolicy: CompanyRemotePolicy.FLEXIBLE,
    companyCategory: CompanyCategory.SOFTWARE,
    companySize: "5000+",
    foundedYear: 1993,
    stackTags: ["Linux", "Cloud", "Backend", "Open source"],
    gameTags: [],
    roleFocusTags: ["Software engineer", "Platform engineer", "Backend engineer"],
    industryTags: ["Cloud", "Developer platform"],
    hiringSignals: ["Large engineering org", "Open-source culture"],
    atsProviders: ["Workday/Other"],
    emailPatterns: ["first.last@redhat.com"],
    notes: "One of the best software targets in North Carolina for platform and systems roles.",
    outreachTips: "Highlight strong fundamentals, developer empathy, and shipped software projects.",
    linkedinUrl: "https://www.linkedin.com/company/red-hat/",
    activeHiring: true,
    contacts: [{ name: "University Programs", title: "Talent Acquisition", notes: "Good outreach target for early-career roles." }],
  }),
  c({
    name: "Pendo",
    slug: "pendo",
    websiteUrl: "https://www.pendo.io",
    careersUrl: "https://www.pendo.io/careers/",
    headquarters: "Raleigh, NC",
    hiringRegions: ["US"],
    locations: ["Raleigh, NC", "New York, NY"],
    remotePolicy: CompanyRemotePolicy.HYBRID,
    companyCategory: CompanyCategory.SOFTWARE,
    companySize: "1000-5000",
    foundedYear: 2013,
    stackTags: ["React", "TypeScript", "Backend", "Product analytics"],
    gameTags: [],
    roleFocusTags: ["Software engineer", "Frontend engineer", "Full stack engineer"],
    industryTags: ["Product software", "Analytics"],
    hiringSignals: ["Product engineering", "UX-sensitive work"],
    atsProviders: ["Greenhouse/Other"],
    emailPatterns: ["first.last@pendo.io"],
    notes: "Excellent local product engineering target if you want polished user-facing software.",
    outreachTips: "Lead with HCI work, frontend polish, and outcome-focused product features.",
    linkedinUrl: "https://www.linkedin.com/company/pendo-io/",
    activeHiring: true,
    contacts: [{ name: "Engineering Recruiting", title: "Talent Acquisition", notes: "Good fit for product and frontend conversations." }],
  }),
  c({
    name: "Bandwidth",
    slug: "bandwidth",
    websiteUrl: "https://www.bandwidth.com",
    careersUrl: "https://www.bandwidth.com/careers/",
    headquarters: "Raleigh, NC",
    hiringRegions: ["US"],
    locations: ["Raleigh, NC"],
    remotePolicy: CompanyRemotePolicy.HYBRID,
    companyCategory: CompanyCategory.SOFTWARE,
    companySize: "1000-5000",
    foundedYear: 1999,
    stackTags: ["Backend", "Telecom APIs", "Distributed systems"],
    gameTags: [],
    roleFocusTags: ["Software engineer", "Backend engineer"],
    industryTags: ["Communications platform"],
    hiringSignals: ["API products", "Platform engineering"],
    atsProviders: ["Greenhouse/Other"],
    emailPatterns: ["first.last@bandwidth.com"],
    notes: "Strong Raleigh target for backend and platform work.",
    outreachTips: "Use examples of reliability, systems thinking, and user-facing product quality.",
    linkedinUrl: "https://www.linkedin.com/company/bandwidth-inc-/",
    activeHiring: true,
    contacts: [{ name: "Tech Recruiting", title: "Talent Acquisition", notes: "Search Raleigh plus software engineer recruiter." }],
  }),
  c({
    name: "SAS",
    slug: "sas",
    websiteUrl: "https://www.sas.com",
    careersUrl: "https://www.sas.com/en_us/careers.html",
    headquarters: "Cary, NC",
    hiringRegions: ["US"],
    locations: ["Cary, NC"],
    remotePolicy: CompanyRemotePolicy.HYBRID,
    companyCategory: CompanyCategory.SOFTWARE,
    companySize: "5000+",
    foundedYear: 1976,
    stackTags: ["Enterprise software", "Cloud", "Analytics"],
    gameTags: [],
    roleFocusTags: ["Software engineer", "Frontend engineer", "Cloud engineer"],
    industryTags: ["Analytics", "Enterprise software"],
    hiringSignals: ["Large NC engineering org"],
    atsProviders: ["Workday/Other"],
    emailPatterns: ["first.last@sas.com"],
    notes: "A strong Cary software employer with broad engineering teams.",
    outreachTips: "Emphasize clean interfaces, problem-solving, and cross-functional communication.",
    linkedinUrl: "https://www.linkedin.com/company/sas/",
    activeHiring: true,
    contacts: [{ name: "Campus Recruiting", title: "Talent Acquisition", notes: "Good place for early-career outreach." }],
  }),
  c({
    name: "nCino",
    slug: "ncino",
    websiteUrl: "https://www.ncino.com",
    careersUrl: "https://www.ncino.com/company/careers/",
    headquarters: "Wilmington, NC",
    hiringRegions: ["US"],
    locations: ["Wilmington, NC"],
    remotePolicy: CompanyRemotePolicy.HYBRID,
    companyCategory: CompanyCategory.SOFTWARE,
    companySize: "1000-5000",
    foundedYear: 2012,
    stackTags: ["Cloud", "Full stack", "Enterprise product"],
    gameTags: [],
    roleFocusTags: ["Software engineer", "Full stack engineer"],
    industryTags: ["Fintech", "Product software"],
    hiringSignals: ["Growing engineering org"],
    atsProviders: ["Greenhouse/Other"],
    emailPatterns: ["first.last@ncino.com"],
    notes: "Useful North Carolina fintech target for general software roles.",
    outreachTips: "Frame yourself as a fast-learning engineer who can ship product features cleanly.",
    linkedinUrl: "https://www.linkedin.com/company/ncino-inc-/",
    activeHiring: true,
    contacts: [{ name: "Talent Acquisition", title: "Recruiting", notes: "Search Wilmington engineering recruiter." }],
  }),
  c({
    name: "AvidXchange",
    slug: "avidxchange",
    websiteUrl: "https://www.avidxchange.com",
    careersUrl: "https://www.avidxchange.com/company/careers/",
    headquarters: "Charlotte, NC",
    hiringRegions: ["US"],
    locations: ["Charlotte, NC"],
    remotePolicy: CompanyRemotePolicy.HYBRID,
    companyCategory: CompanyCategory.SOFTWARE,
    companySize: "1000-5000",
    foundedYear: 2000,
    stackTags: ["Full stack", "Fintech", "Cloud"],
    gameTags: [],
    roleFocusTags: ["Software engineer", "Backend engineer", "Frontend engineer"],
    industryTags: ["Fintech", "B2B software"],
    hiringSignals: ["Charlotte engineering hub"],
    atsProviders: ["Greenhouse/Other"],
    emailPatterns: ["first.last@avidxchange.com"],
    notes: "Useful Charlotte software target with broad product work.",
    outreachTips: "Stress ownership, implementation quality, and product impact.",
    linkedinUrl: "https://www.linkedin.com/company/avidxchange-inc-/",
    activeHiring: true,
    contacts: [{ name: "Recruiting Team", title: "Talent Acquisition", notes: "Search Charlotte engineering recruiter." }],
  }),
  c({
    name: "Lowe's Tech",
    slug: "lowes-tech",
    websiteUrl: "https://www.lowes.com",
    careersUrl: "https://talent.lowes.com/us/en/technology",
    headquarters: "Charlotte, NC",
    hiringRegions: ["US"],
    locations: ["Charlotte, NC", "Remote US"],
    remotePolicy: CompanyRemotePolicy.FLEXIBLE,
    companyCategory: CompanyCategory.SOFTWARE,
    companySize: "5000+",
    foundedYear: 1946,
    stackTags: ["Full stack", "Cloud", "Mobile", "Platform"],
    gameTags: [],
    roleFocusTags: ["Software engineer", "Mobile engineer", "Platform engineer"],
    industryTags: ["Retail technology"],
    hiringSignals: ["Large engineering org", "Enterprise scale"],
    atsProviders: ["Workday/Other"],
    emailPatterns: ["first.last@lowes.com"],
    notes: "Worth tracking for broad software roles in Charlotte.",
    outreachTips: "Connect classroom communication and product-minded engineering to customer-facing tech.",
    linkedinUrl: "https://www.linkedin.com/company/lowe-s-companies-inc-/",
    activeHiring: true,
    contacts: [{ name: "Tech Recruiting", title: "Talent Acquisition", notes: "Search Lowe's technology recruiter." }],
  }),
  c({
    name: "Credit Karma",
    slug: "credit-karma-charlotte",
    websiteUrl: "https://www.creditkarma.com",
    careersUrl: "https://www.creditkarma.com/careers",
    headquarters: "Charlotte, NC",
    hiringRegions: ["US"],
    locations: ["Charlotte, NC", "Remote US"],
    remotePolicy: CompanyRemotePolicy.FLEXIBLE,
    companyCategory: CompanyCategory.SOFTWARE,
    companySize: "1000-5000",
    foundedYear: 2007,
    stackTags: ["Frontend", "Backend", "Consumer product"],
    gameTags: [],
    roleFocusTags: ["Software engineer", "Frontend engineer", "Product engineer"],
    industryTags: ["Consumer fintech"],
    hiringSignals: ["Product engineering", "Consumer-scale systems"],
    atsProviders: ["Greenhouse/Other"],
    emailPatterns: ["first.last@creditkarma.com"],
    notes: "Good consumer product target with a North Carolina presence.",
    outreachTips: "Pitch clean UX, frontend polish, and end-user empathy.",
    linkedinUrl: "https://www.linkedin.com/company/credit-karma/",
    activeHiring: true,
    contacts: [{ name: "Talent Partner", title: "Recruiting", notes: "Search by office and product team." }],
  }),
  c({
    name: "OpenAI",
    slug: "openai",
    websiteUrl: "https://openai.com",
    careersUrl: "https://openai.com/careers/",
    headquarters: "San Francisco, CA",
    hiringRegions: ["US", "Global select"],
    locations: ["San Francisco, CA", "New York, NY"],
    remotePolicy: CompanyRemotePolicy.HYBRID,
    companyCategory: CompanyCategory.SOFTWARE,
    companySize: "1000-5000",
    foundedYear: 2015,
    stackTags: ["Python", "Distributed systems", "Product engineering", "Infrastructure"],
    gameTags: [],
    roleFocusTags: ["Software engineer", "Product engineer", "Infrastructure engineer"],
    industryTags: ["AI", "Software"],
    hiringSignals: ["High-growth engineering org"],
    atsProviders: ["Greenhouse"],
    emailPatterns: ["first@openai.com", "first.last@openai.com"],
    notes: "A stretch target with strong software engineering and product opportunities.",
    outreachTips: "Use concrete engineering outcomes and polished user-facing systems, not generic AI enthusiasm.",
    linkedinUrl: "https://www.linkedin.com/company/openai/",
    activeHiring: true,
    contacts: [{ name: "Talent Partner", title: "Recruiting", notes: "Prioritize specific team recruiters rather than general inboxes." }],
  }),
  c({
    name: "Vercel",
    slug: "vercel",
    websiteUrl: "https://vercel.com",
    careersUrl: "https://vercel.com/careers",
    headquarters: "San Francisco, CA",
    hiringRegions: ["US", "Remote"],
    locations: ["Remote", "San Francisco, CA"],
    remotePolicy: CompanyRemotePolicy.REMOTE_FRIENDLY,
    companyCategory: CompanyCategory.SOFTWARE,
    companySize: "500-1000",
    foundedYear: 2015,
    stackTags: ["TypeScript", "Next.js", "Cloud", "Developer tools"],
    gameTags: [],
    roleFocusTags: ["Frontend engineer", "Full stack engineer", "Developer experience"],
    industryTags: ["Developer platform", "Cloud"],
    hiringSignals: ["Remote-first", "Developer tooling"],
    atsProviders: ["Ashby"],
    emailPatterns: ["first@vercel.com", "first.last@vercel.com"],
    notes: "Great fit for React, TypeScript, frontend platform, and developer UX work.",
    outreachTips: "Mention polished frontend experiences, performance, tooling, or developer workflows.",
    linkedinUrl: "https://www.linkedin.com/company/vercel/",
    activeHiring: true,
    contacts: [{ name: "Hiring Team", title: "Talent Acquisition", notes: "Ashby page plus LinkedIn recruiter search is a good combo." }],
  }),
  c({
    name: "Figma",
    slug: "figma",
    websiteUrl: "https://www.figma.com",
    careersUrl: "https://www.figma.com/careers/",
    headquarters: "San Francisco, CA",
    hiringRegions: ["US"],
    locations: ["San Francisco, CA", "New York, NY"],
    remotePolicy: CompanyRemotePolicy.HYBRID,
    companyCategory: CompanyCategory.SOFTWARE,
    companySize: "1000-5000",
    foundedYear: 2012,
    stackTags: ["TypeScript", "Web app", "Frontend systems", "Collaboration"],
    gameTags: [],
    roleFocusTags: ["Software engineer", "Frontend engineer", "Product engineer"],
    industryTags: ["Design software", "Collaboration"],
    hiringSignals: ["High bar for product feel", "Frontend heavy"],
    atsProviders: ["Greenhouse"],
    emailPatterns: ["first@figma.com", "first.last@figma.com"],
    notes: "Strong target for UX-sensitive engineers because your HCI background is relevant.",
    outreachTips: "Lead with HCI lab work, interface polish, and user-centered implementation.",
    linkedinUrl: "https://www.linkedin.com/company/figma/",
    activeHiring: true,
    contacts: [{ name: "Engineering Recruiting", title: "Talent Acquisition", notes: "Tie outreach to product quality and interaction design." }],
  }),
  c({
    name: "Notion",
    slug: "notion",
    websiteUrl: "https://www.notion.so",
    careersUrl: "https://www.notion.so/careers",
    headquarters: "San Francisco, CA",
    hiringRegions: ["US", "Remote select"],
    locations: ["San Francisco, CA", "New York, NY"],
    remotePolicy: CompanyRemotePolicy.FLEXIBLE,
    companyCategory: CompanyCategory.SOFTWARE,
    companySize: "1000-5000",
    foundedYear: 2016,
    stackTags: ["Full stack", "Product engineering", "Frontend"],
    gameTags: [],
    roleFocusTags: ["Software engineer", "Product engineer"],
    industryTags: ["Productivity software"],
    hiringSignals: ["Strong product engineering culture"],
    atsProviders: ["Greenhouse"],
    emailPatterns: ["first@makenotion.com", "first.last@makenotion.com"],
    notes: "Good fit for product-minded full stack and frontend roles.",
    outreachTips: "Use examples of end-user impact, usability, and clean execution.",
    linkedinUrl: "https://www.linkedin.com/company/notionhq/",
    activeHiring: true,
    contacts: [{ name: "Recruiting Team", title: "Talent Acquisition", notes: "Search for product engineering recruiters." }],
  }),
  c({
    name: "Discord",
    slug: "discord",
    websiteUrl: "https://discord.com",
    careersUrl: "https://discord.com/jobs",
    headquarters: "San Francisco, CA",
    hiringRegions: ["US", "Remote US"],
    locations: ["San Francisco, CA", "Remote US"],
    remotePolicy: CompanyRemotePolicy.REMOTE_FRIENDLY,
    companyCategory: CompanyCategory.BOTH,
    companySize: "1000-5000",
    foundedYear: 2015,
    stackTags: ["TypeScript", "React", "Backend", "Infrastructure"],
    gameTags: ["Gaming community", "Social platform"],
    roleFocusTags: ["Software engineer", "Frontend engineer", "Backend engineer"],
    industryTags: ["Consumer software", "Gaming"],
    hiringSignals: ["Remote roles", "Strong product engineering"],
    atsProviders: ["Lever"],
    emailPatterns: ["first.last@discord.com"],
    notes: "A good target if you want software engineering with gaming adjacency.",
    outreachTips: "Pitch community tools, product polish, frontend work, and systems that improve user experience.",
    linkedinUrl: "https://www.linkedin.com/company/discordapp/",
    activeHiring: true,
    contacts: [{ name: "Engineering Recruiting", title: "Talent Acquisition", notes: "Search by team plus recruiter on LinkedIn." }],
  }),
  c({
    name: "Unity",
    slug: "unity",
    websiteUrl: "https://unity.com",
    careersUrl: "https://careers.unity.com",
    headquarters: "San Francisco, CA",
    hiringRegions: ["US", "Remote eligible roles"],
    locations: ["San Francisco, CA", "Bellevue, WA", "Remote"],
    remotePolicy: CompanyRemotePolicy.FLEXIBLE,
    companyCategory: CompanyCategory.BOTH,
    companySize: "5000+",
    foundedYear: 2004,
    stackTags: ["C#", "Graphics", "Engine", "Developer tools"],
    gameTags: ["Unity", "Game tech", "Runtime"],
    roleFocusTags: ["Software engineer", "Engine programmer", "Developer relations"],
    industryTags: ["Game engine", "Software platform"],
    hiringSignals: ["Engine teams", "Developer platform", "Gaming-adjacent software"],
    atsProviders: ["Greenhouse"],
    emailPatterns: ["first.last@unity.com"],
    notes: "Good bridge company between game tech and software engineering.",
    outreachTips: "Lead with Unity projects, editor tooling, gameplay systems, and dev workflow improvements.",
    linkedinUrl: "https://www.linkedin.com/company/unity-technologies/",
    activeHiring: true,
    contacts: [{ name: "Developer Hiring Team", title: "Talent Acquisition", notes: "Search for recruiter + Unity + engineering on LinkedIn." }],
  }),
  c({
    name: "Roblox",
    slug: "roblox",
    websiteUrl: "https://corp.roblox.com",
    careersUrl: "https://careers.roblox.com/jobs",
    headquarters: "San Mateo, CA",
    hiringRegions: ["US", "Remote select"],
    locations: ["San Mateo, CA", "Remote US"],
    remotePolicy: CompanyRemotePolicy.FLEXIBLE,
    companyCategory: CompanyCategory.BOTH,
    companySize: "1000-5000",
    foundedYear: 2004,
    stackTags: ["C++", "Lua", "Distributed systems", "Platform"],
    gameTags: ["UGC platform", "Engine", "Simulation"],
    roleFocusTags: ["Software engineer", "Engine programmer", "Gameplay systems"],
    industryTags: ["Gaming platform", "Creator economy"],
    hiringSignals: ["Large platform engineering org", "Graphics and engine"],
    atsProviders: ["Greenhouse"],
    emailPatterns: ["first.last@roblox.com"],
    notes: "Great mix of large-scale software plus game technology.",
    outreachTips: "Highlight both gameplay systems and scalable product thinking.",
    linkedinUrl: "https://www.linkedin.com/company/roblox/",
    activeHiring: true,
    contacts: [{ name: "University Recruiting", title: "Talent Acquisition", notes: "Good target for entry-level and internship outreach." }],
  }),
  c({
    name: "Riot Games",
    slug: "riot-games",
    websiteUrl: "https://www.riotgames.com",
    careersUrl: "https://www.riotgames.com/en/work-with-us/jobs",
    headquarters: "Los Angeles, CA",
    hiringRegions: ["US"],
    locations: ["Los Angeles, CA", "Remote select"],
    remotePolicy: CompanyRemotePolicy.FLEXIBLE,
    companyCategory: CompanyCategory.GAMING,
    companySize: "5000+",
    foundedYear: 2006,
    stackTags: ["C++", "Java", "Backend", "Tools"],
    gameTags: ["Gameplay", "Live service", "Player systems"],
    roleFocusTags: ["Gameplay engineer", "Software engineer", "Tools engineer"],
    industryTags: ["Game development", "Esports"],
    hiringSignals: ["Large live-service engineering org"],
    atsProviders: ["Greenhouse/Other"],
    emailPatterns: [],
    notes: "Use shipped gameplay systems and polish examples here.",
    outreachTips: "Connect your work to player experience, responsiveness, and readable combat systems.",
    linkedinUrl: "https://www.linkedin.com/company/riot-games/",
    activeHiring: true,
    contacts: [{ name: "Talent Team", title: "Recruiting", notes: "Search by discipline and office on LinkedIn." }],
  }),
  c({
    name: "Niantic Spatial",
    slug: "niantic-spatial",
    websiteUrl: "https://nianticspatial.com",
    careersUrl: "https://nianticspatial.com/careers",
    headquarters: "San Francisco, CA",
    hiringRegions: ["US"],
    locations: ["San Francisco, CA"],
    remotePolicy: CompanyRemotePolicy.HYBRID,
    companyCategory: CompanyCategory.BOTH,
    companySize: "200-500",
    foundedYear: 2010,
    stackTags: ["Unity", "AR", "Mobile", "Backend"],
    gameTags: ["AR", "Location-based games"],
    roleFocusTags: ["Unity engineer", "Software engineer"],
    industryTags: ["AR", "Gaming", "Spatial computing"],
    hiringSignals: ["Cross-disciplinary product/game work"],
    atsProviders: ["Greenhouse/Other"],
    emailPatterns: [],
    notes: "Relevant if you want Unity plus product/software crossover.",
    outreachTips: "Connect your Unity mechanics work and UI sensibility to live player-facing systems.",
    linkedinUrl: "https://www.linkedin.com/company/nianticinc/",
    activeHiring: true,
    contacts: [{ name: "Talent Partner", title: "Recruiting", notes: "Look for engineering recruiters or studio leadership on LinkedIn." }],
  }),
  // More software targets
  ...[
    ["Stripe", "stripe", "South San Francisco, CA", ["Backend", "Distributed systems", "API platform"], ["Software engineer", "Backend engineer"], "Greenhouse"],
    ["Datadog", "datadog", "New York, NY", ["Cloud", "Infrastructure", "Developer tools"], ["Software engineer", "Full stack engineer"], "Greenhouse"],
    ["Shopify", "shopify", "Remote", ["Ruby", "React", "Product engineering"], ["Software engineer", "Frontend engineer"], "Greenhouse/Other"],
    ["Atlassian", "atlassian", "Remote", ["Cloud", "Full stack", "Developer tools"], ["Software engineer", "Frontend engineer"], "Greenhouse/Other"],
    ["Plaid", "plaid", "San Francisco, CA", ["Fintech", "Backend", "API platform"], ["Software engineer", "Backend engineer"], "Lever"],
    ["Brex", "brex", "Remote", ["Fintech", "Full stack", "Product engineering"], ["Software engineer", "Full stack engineer"], "Lever"],
    ["Ramp", "ramp", "New York, NY", ["Fintech", "Product engineering", "Full stack"], ["Software engineer", "Product engineer"], "Ashby"],
    ["Anthropic", "anthropic", "San Francisco, CA", ["Python", "Distributed systems", "Infrastructure"], ["Software engineer", "Product engineer"], "Ashby"],
    ["Perplexity", "perplexity", "San Francisco, CA", ["Frontend", "Backend", "AI product"], ["Software engineer", "Frontend engineer"], "Ashby"],
    ["Runway", "runway", "New York, NY", ["Frontend", "Backend", "Creative tools"], ["Software engineer", "Product engineer"], "Ashby"],
    ["Canva", "canva", "San Francisco, CA", ["Frontend", "Full stack", "Design tooling"], ["Software engineer", "Frontend engineer"], "Greenhouse"],
    ["Asana", "asana", "San Francisco, CA", ["Frontend", "Backend", "Collaboration"], ["Software engineer", "Product engineer"], "Greenhouse"],
    ["Dropbox", "dropbox", "Remote", ["Frontend", "Backend", "Infrastructure"], ["Software engineer", "Full stack engineer"], "Greenhouse/Other"],
    ["Pinterest", "pinterest", "San Francisco, CA", ["Frontend", "Backend", "Consumer product"], ["Software engineer", "Frontend engineer"], "Greenhouse/Other"],
    ["Reddit", "reddit", "Remote", ["Backend", "Frontend", "Consumer product"], ["Software engineer", "Product engineer"], "Greenhouse/Other"],
    ["Snap", "snap", "Santa Monica, CA", ["Frontend", "Mobile", "AR"], ["Software engineer", "Product engineer"], "Greenhouse/Other"],
    ["Coinbase", "coinbase", "Remote", ["Backend", "Infrastructure", "Consumer finance"], ["Software engineer", "Backend engineer"], "Greenhouse"],
    ["Airtable", "airtable", "San Francisco, CA", ["Frontend", "Backend", "Product engineering"], ["Software engineer", "Frontend engineer"], "Greenhouse"],
    ["Linear", "linear", "Remote", ["TypeScript", "Frontend", "Product engineering"], ["Software engineer", "Product engineer"], "Ashby"],
    ["Clerk", "clerk", "Remote", ["TypeScript", "Developer tools", "Auth"], ["Software engineer", "Full stack engineer"], "Ashby"],
    ["Postman", "postman", "San Francisco, CA", ["Frontend", "Backend", "Developer tools"], ["Software engineer", "Frontend engineer"], "Lever"],
  ].map(([name, slug, headquarters, stackTags, roleFocusTags, ats]) => c({
    name: String(name),
    slug: String(slug),
    websiteUrl: undefined,
    careersUrl: undefined,
    headquarters: String(headquarters),
    hiringRegions: ["US", "Remote select"],
    locations: [String(headquarters)],
    remotePolicy: /remote/i.test(String(headquarters)) ? CompanyRemotePolicy.REMOTE_FRIENDLY : CompanyRemotePolicy.FLEXIBLE,
    companyCategory: CompanyCategory.SOFTWARE,
    companySize: "1000-5000",
    foundedYear: undefined,
    stackTags: stackTags as string[],
    gameTags: [],
    roleFocusTags: roleFocusTags as string[],
    industryTags: ["Software"],
    hiringSignals: ["Engineering org", "Good software target"],
    atsProviders: [String(ats)],
    emailPatterns: [],
    notes: "Added as a high-signal software target for the outreach and jobs pipeline.",
    outreachTips: "Focus your outreach on team fit, product impact, and relevant stack overlap.",
    linkedinUrl: undefined,
    activeHiring: true,
    contacts: [{ name: "Talent Acquisition", title: "Recruiting", notes: "Use a recruiter search plus target team keywords." }],
  })),
  // More game targets
  ...[
    ["Electronic Arts", "ea", "Redwood City, CA", ["C++", "Backend", "Tools"], ["Software engineer", "Gameplay engineer"], ["Live games", "Game development"], "Greenhouse/Other"],
    ["Blizzard Entertainment", "blizzard-entertainment", "Irvine, CA", ["C++", "Tools", "Gameplay"], ["Gameplay engineer", "Tools engineer"], ["Game development"], "Greenhouse/Other"],
    ["PlayStation", "playstation", "San Mateo, CA", ["C++", "Platform", "Backend"], ["Software engineer", "Gameplay engineer"], ["Gaming platform"], "Greenhouse/Other"],
    ["Zynga", "zynga", "San Francisco, CA", ["Mobile", "Backend", "Live ops"], ["Software engineer", "Gameplay engineer"], ["Mobile games"], "Greenhouse/Other"],
    ["Supercell", "supercell", "Remote", ["Gameplay", "Backend", "Live ops"], ["Gameplay engineer", "Software engineer"], ["Mobile games"], "Greenhouse/Other"],
    ["Bungie", "bungie", "Bellevue, WA", ["C++", "Gameplay", "Online systems"], ["Gameplay engineer", "Tools engineer"], ["Game development"], "Workday/Other"],
    ["Respawn Entertainment", "respawn-entertainment", "Los Angeles, CA", ["C++", "Gameplay", "Tools"], ["Gameplay engineer", "Tools engineer"], ["Game development"], "Workday/Other"],
    ["Digital Extremes", "digital-extremes", "Remote", ["C++", "Gameplay", "Online systems"], ["Gameplay engineer", "Software engineer"], ["Game development"], "Direct careers page"],
    ["Moonshot Games", "moonshot-games", "Remote", ["Gameplay", "Systems", "Multiplayer"], ["Gameplay engineer", "Generalist programmer"], ["Game development"], "Direct careers page"],
    ["Second Dinner", "second-dinner", "Remote", ["Unity", "C#", "Gameplay"], ["Unity engineer", "Gameplay engineer"], ["Game development"], "Direct careers page"],
  ].map(([name, slug, headquarters, stackTags, roleFocusTags, industryTags, ats]) => c({
    name: String(name),
    slug: String(slug),
    websiteUrl: undefined,
    careersUrl: undefined,
    headquarters: String(headquarters),
    hiringRegions: ["US", "Remote select"],
    locations: [String(headquarters)],
    remotePolicy: /remote/i.test(String(headquarters)) ? CompanyRemotePolicy.REMOTE_FRIENDLY : CompanyRemotePolicy.FLEXIBLE,
    companyCategory: CompanyCategory.GAMING,
    companySize: "1000-5000",
    foundedYear: undefined,
    stackTags: stackTags as string[],
    gameTags: ["Gameplay", "Games"],
    roleFocusTags: roleFocusTags as string[],
    industryTags: industryTags as string[],
    hiringSignals: ["Game studio target", "Good fit for gameplay and systems outreach"],
    atsProviders: [String(ats)],
    emailPatterns: [],
    notes: "Added as a high-signal game company target for the outreach and jobs pipeline.",
    outreachTips: "Lead with movement, combat feel, responsive systems, and any engine/tooling work.",
    linkedinUrl: undefined,
    activeHiring: true,
    contacts: [{ name: "Studio Recruiting", title: "Talent Acquisition", notes: "Search recruiter plus gameplay or engineering manager for this studio." }],
  })),
] as const;

const seededJobs = [
  {
    source: "seed",
    externalId: "seed-1",
    sourceUrl: "https://example.com/jobs/1",
    applyUrl: "https://example.com/jobs/1/apply",
    title: "Junior Gameplay Programmer",
    company: "Methodical Games",
    location: "Raleigh, NC",
    workplaceType: WorkplaceType.HYBRID,
    employmentType: EmploymentType.FULL_TIME,
    experienceLevel: ExperienceLevel.ENTRY,
    descriptionText: "Build player systems, tools, and game feel for a stylized action-platformer.",
    postedAt: new Date(),
    tags: JSON.stringify(["Unity", "C#", "Gameplay"]),
  },
  {
    source: "seed",
    externalId: "seed-2",
    sourceUrl: "https://example.com/jobs/2",
    applyUrl: "https://example.com/jobs/2/apply",
    title: "Software Engineering Intern",
    company: "Pendo",
    location: "Raleigh, NC",
    workplaceType: WorkplaceType.HYBRID,
    employmentType: EmploymentType.INTERNSHIP,
    experienceLevel: ExperienceLevel.INTERN,
    descriptionText: "Support web platform development for internal creator tools.",
    postedAt: new Date(),
    tags: JSON.stringify(["React", "TypeScript", "Internship"]),
  },
  {
    source: "seed",
    externalId: "seed-3",
    sourceUrl: "https://example.com/jobs/3",
    applyUrl: "https://example.com/jobs/3/apply",
    title: "Associate Software Engineer",
    company: "Red Hat",
    location: "Raleigh, NC",
    workplaceType: WorkplaceType.HYBRID,
    employmentType: EmploymentType.FULL_TIME,
    experienceLevel: ExperienceLevel.ENTRY,
    descriptionText: "Work on platform features, APIs, and developer tooling for cloud infrastructure.",
    postedAt: new Date(),
    tags: JSON.stringify(["Linux", "Cloud", "Backend", "Developer tools"]),
  },
  {
    source: "seed",
    externalId: "seed-4",
    sourceUrl: "https://example.com/jobs/4",
    applyUrl: "https://example.com/jobs/4/apply",
    title: "Gameplay Engineer",
    company: "Epic Games",
    location: "Cary, NC",
    workplaceType: WorkplaceType.HYBRID,
    employmentType: EmploymentType.FULL_TIME,
    experienceLevel: ExperienceLevel.MID,
    descriptionText: "Implement gameplay features, movement systems, and combat interactions in Unreal.",
    postedAt: new Date(),
    tags: JSON.stringify(["Gameplay", "C++", "Unreal Engine"]),
  },
];

async function main() {
  await prisma.application.deleteMany();
  await prisma.job.deleteMany();
  await prisma.companyContact.deleteMany();
  await prisma.company.deleteMany();

  await prisma.job.createMany({ data: seededJobs });

  for (const company of companies) {
    const { contacts, ...companyData } = company;
    await prisma.company.create({
      data: {
        ...companyData,
        contacts: {
          create: contacts,
        },
      },
    });
  }
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (error) => {
    console.error(error);
    await prisma.$disconnect();
    process.exit(1);
  });
