/**
 * Non-destructive company seeder — uses upsert so it never wipes existing data.
 * Run: npm run seed:companies
 */
import { prisma } from "../lib/db";

type SeedCompany = {
  name: string;
  slug: string;
  websiteUrl?: string;
  careersUrl?: string;
  headquarters?: string;
  hiringRegions: string[];
  locations: string[];
  remotePolicy: "REMOTE_FRIENDLY" | "FLEXIBLE" | "HYBRID" | "ONSITE" | "REMOTE_FIRST";
  companyCategory: "SOFTWARE" | "GAMING" | "BOTH";
  companySize?: string;
  stackTags: string[];
  gameTags: string[];
  roleFocusTags: string[];
  industryTags: string[];
  atsProviders: string[];
  notes?: string;
  activeHiring: boolean;
};

function s(x: string[]): string { return JSON.stringify(x); }

const companies: SeedCompany[] = [
  // ── North Carolina ──────────────────────────────────────────────
  {
    name: "Red Hat",
    slug: "red-hat",
    websiteUrl: "https://www.redhat.com",
    careersUrl: "https://www.redhat.com/en/jobs",
    headquarters: "Raleigh, NC",
    hiringRegions: ["US", "Remote"],
    locations: ["Raleigh, NC", "Remote"],
    remotePolicy: "REMOTE_FRIENDLY",
    companyCategory: "SOFTWARE",
    companySize: "10,000+",
    stackTags: ["Linux", "Kubernetes", "OpenShift", "Ansible", "Go", "Python", "Java"],
    gameTags: [],
    roleFocusTags: ["backend", "devops", "platform", "cloud"],
    industryTags: ["open source", "enterprise", "cloud"],
    atsProviders: ["Workday"],
    notes: "Major open-source software company (IBM subsidiary). HQ in Raleigh.",
    activeHiring: true,
  },
  {
    name: "Bandwidth",
    slug: "bandwidth",
    websiteUrl: "https://www.bandwidth.com",
    careersUrl: "https://www.bandwidth.com/careers",
    headquarters: "Raleigh, NC",
    hiringRegions: ["US", "Remote"],
    locations: ["Raleigh, NC"],
    remotePolicy: "HYBRID",
    companyCategory: "SOFTWARE",
    companySize: "501–2,000",
    stackTags: ["C++", "Go", "Python", "AWS", "React", "TypeScript"],
    gameTags: [],
    roleFocusTags: ["backend", "platform", "cloud", "voice"],
    industryTags: ["communications", "CPaaS", "telecom"],
    atsProviders: ["Greenhouse"],
    notes: "Cloud communications platform for enterprise voice, messaging, and 911 services.",
    activeHiring: true,
  },
  {
    name: "Pendo",
    slug: "pendo",
    websiteUrl: "https://www.pendo.io",
    careersUrl: "https://www.pendo.io/jobs",
    headquarters: "Raleigh, NC",
    hiringRegions: ["US", "Remote"],
    locations: ["Raleigh, NC", "Remote"],
    remotePolicy: "REMOTE_FRIENDLY",
    companyCategory: "SOFTWARE",
    companySize: "501–2,000",
    stackTags: ["React", "TypeScript", "Go", "Python", "AWS"],
    gameTags: [],
    roleFocusTags: ["frontend", "backend", "product analytics"],
    industryTags: ["product analytics", "SaaS", "PLG"],
    atsProviders: ["Greenhouse"],
    notes: "Product analytics and in-app guidance platform. Strong engineering culture in Raleigh.",
    activeHiring: true,
  },
  {
    name: "Epic Games",
    slug: "epic-games",
    websiteUrl: "https://www.epicgames.com",
    careersUrl: "https://www.epicgames.com/site/en-US/careers",
    headquarters: "Cary, NC",
    hiringRegions: ["US", "Europe", "Remote"],
    locations: ["Cary, NC", "Remote"],
    remotePolicy: "REMOTE_FRIENDLY",
    companyCategory: "GAMING",
    companySize: "5,001–10,000",
    stackTags: ["C++", "Unreal Engine", "Python", "AWS", "TypeScript"],
    gameTags: ["Unreal Engine", "Fortnite", "metaverse", "3D"],
    roleFocusTags: ["game programming", "graphics", "tools", "platform"],
    industryTags: ["AAA games", "game engine", "metaverse"],
    atsProviders: ["Workday"],
    notes: "Maker of Fortnite and Unreal Engine. World HQ in Cary, NC.",
    activeHiring: true,
  },
  {
    name: "Sabre Industries",
    slug: "sabre88",
    websiteUrl: "https://www.sabre88.com",
    careersUrl: "https://sabre88.com/careers",
    headquarters: "Raleigh, NC",
    hiringRegions: ["US"],
    locations: ["Raleigh, NC"],
    remotePolicy: "HYBRID",
    companyCategory: "SOFTWARE",
    companySize: "51–200",
    stackTags: ["Java", "Python", "AWS", "React"],
    gameTags: [],
    roleFocusTags: ["backend", "cloud", "security"],
    industryTags: ["defense", "government", "IT services"],
    atsProviders: [],
    notes: "Government IT and cybersecurity services firm in Research Triangle.",
    activeHiring: true,
  },
  {
    name: "Cree Wolfspeed",
    slug: "wolfspeed",
    websiteUrl: "https://www.wolfspeed.com",
    careersUrl: "https://www.wolfspeed.com/company/careers",
    headquarters: "Durham, NC",
    hiringRegions: ["US"],
    locations: ["Durham, NC", "Marcy, NY"],
    remotePolicy: "ONSITE",
    companyCategory: "SOFTWARE",
    companySize: "2,001–5,000",
    stackTags: ["Python", "MATLAB", "C", "embedded"],
    gameTags: [],
    roleFocusTags: ["embedded", "firmware", "hardware"],
    industryTags: ["semiconductors", "power electronics", "clean energy"],
    atsProviders: ["Workday"],
    notes: "SiC semiconductor company with major Durham footprint. Embedded/firmware roles.",
    activeHiring: true,
  },
  {
    name: "Dude Solutions",
    slug: "dude-solutions",
    websiteUrl: "https://www.dudesolutions.com",
    careersUrl: "https://www.dudesolutions.com/about/careers",
    headquarters: "Cary, NC",
    hiringRegions: ["US", "Remote"],
    locations: ["Cary, NC", "Remote"],
    remotePolicy: "REMOTE_FRIENDLY",
    companyCategory: "SOFTWARE",
    companySize: "201–500",
    stackTags: ["React", "Node.js", "TypeScript", "AWS", ".NET"],
    gameTags: [],
    roleFocusTags: ["full stack", "backend", "SaaS"],
    industryTags: ["facilities management", "SaaS", "CMMS"],
    atsProviders: ["Greenhouse"],
    notes: "Facilities operations SaaS. Strong tech team in Cary, NC.",
    activeHiring: true,
  },
  {
    name: "Ipreo (IHS Markit)",
    slug: "ipreo",
    websiteUrl: "https://ihsmarkit.com",
    careersUrl: "https://careers.spglobal.com",
    headquarters: "Charlotte, NC",
    hiringRegions: ["US"],
    locations: ["Charlotte, NC"],
    remotePolicy: "HYBRID",
    companyCategory: "SOFTWARE",
    companySize: "1,001–5,000",
    stackTags: ["C#", ".NET", "React", "SQL Server", "Azure"],
    gameTags: [],
    roleFocusTags: ["backend", "data engineering", "fintech"],
    industryTags: ["fintech", "capital markets", "financial data"],
    atsProviders: ["Workday"],
    notes: "Financial data and capital markets software (acquired by IHS Markit / S&P Global).",
    activeHiring: true,
  },
  {
    name: "Lenovo",
    slug: "lenovo",
    websiteUrl: "https://www.lenovo.com",
    careersUrl: "https://jobs.lenovo.com",
    headquarters: "Morrisville, NC",
    hiringRegions: ["US", "Global"],
    locations: ["Morrisville, NC", "Remote"],
    remotePolicy: "FLEXIBLE",
    companyCategory: "SOFTWARE",
    companySize: "50,000+",
    stackTags: ["Python", "C++", "Java", "Cloud", "AI/ML"],
    gameTags: [],
    roleFocusTags: ["software engineering", "AI", "cloud"],
    industryTags: ["hardware", "PC", "enterprise tech"],
    atsProviders: ["Workday"],
    notes: "Global PC and tech manufacturer with North American HQ in Morrisville, NC.",
    activeHiring: true,
  },

  // ── Major US Tech ────────────────────────────────────────────────
  {
    name: "Google",
    slug: "google",
    websiteUrl: "https://www.google.com",
    careersUrl: "https://careers.google.com",
    headquarters: "Mountain View, CA",
    hiringRegions: ["US", "Global"],
    locations: ["Mountain View, CA", "New York, NY", "Seattle, WA", "Austin, TX", "Remote"],
    remotePolicy: "HYBRID",
    companyCategory: "SOFTWARE",
    companySize: "100,000+",
    stackTags: ["Go", "C++", "Python", "Java", "Kotlin", "TypeScript", "TensorFlow", "Kubernetes"],
    gameTags: [],
    roleFocusTags: ["backend", "infrastructure", "ML", "frontend", "SRE"],
    industryTags: ["search", "cloud", "advertising", "AI"],
    atsProviders: ["Greenhouse"],
    notes: "Alphabet subsidiary. Strong SWE culture, rigorous interview process.",
    activeHiring: true,
  },
  {
    name: "Meta",
    slug: "meta",
    websiteUrl: "https://www.meta.com",
    careersUrl: "https://www.metacareers.com",
    headquarters: "Menlo Park, CA",
    hiringRegions: ["US", "Global"],
    locations: ["Menlo Park, CA", "New York, NY", "Seattle, WA", "Austin, TX", "Remote"],
    remotePolicy: "FLEXIBLE",
    companyCategory: "SOFTWARE",
    companySize: "50,000+",
    stackTags: ["React", "Hack/PHP", "Python", "C++", "PyTorch", "Rust", "GraphQL"],
    gameTags: [],
    roleFocusTags: ["frontend", "backend", "ML", "infra", "VR"],
    industryTags: ["social media", "metaverse", "VR/AR", "advertising"],
    atsProviders: ["Workday"],
    notes: "Creator of Facebook, Instagram, WhatsApp, and Quest VR headsets.",
    activeHiring: true,
  },
  {
    name: "Amazon",
    slug: "amazon",
    websiteUrl: "https://www.amazon.com",
    careersUrl: "https://www.amazon.jobs",
    headquarters: "Seattle, WA",
    hiringRegions: ["US", "Global"],
    locations: ["Seattle, WA", "New York, NY", "Austin, TX", "Nashville, TN", "Remote"],
    remotePolicy: "HYBRID",
    companyCategory: "SOFTWARE",
    companySize: "500,000+",
    stackTags: ["Java", "Python", "Go", "AWS", "Rust", "TypeScript", "Kotlin"],
    gameTags: [],
    roleFocusTags: ["backend", "cloud", "SDE", "ML", "DevOps"],
    industryTags: ["e-commerce", "cloud", "logistics", "AI"],
    atsProviders: ["Workday"],
    notes: "AWS, retail, devices, and AI. Leadership principles drive the interview process.",
    activeHiring: true,
  },
  {
    name: "Apple",
    slug: "apple",
    websiteUrl: "https://www.apple.com",
    careersUrl: "https://www.apple.com/careers",
    headquarters: "Cupertino, CA",
    hiringRegions: ["US", "Global"],
    locations: ["Cupertino, CA", "Austin, TX", "New York, NY", "Seattle, WA"],
    remotePolicy: "ONSITE",
    companyCategory: "SOFTWARE",
    companySize: "100,000+",
    stackTags: ["Swift", "Objective-C", "C++", "Python", "Metal", "CoreML"],
    gameTags: [],
    roleFocusTags: ["iOS", "macOS", "ML", "hardware/software"],
    industryTags: ["consumer tech", "mobile", "silicon", "privacy"],
    atsProviders: ["Workday"],
    notes: "Strong design culture. Primarily onsite in Cupertino. Deep Swift/Obj-C stack.",
    activeHiring: true,
  },
  {
    name: "Microsoft",
    slug: "microsoft",
    websiteUrl: "https://www.microsoft.com",
    careersUrl: "https://careers.microsoft.com",
    headquarters: "Redmond, WA",
    hiringRegions: ["US", "Global"],
    locations: ["Redmond, WA", "Seattle, WA", "New York, NY", "Austin, TX", "Remote"],
    remotePolicy: "FLEXIBLE",
    companyCategory: "SOFTWARE",
    companySize: "200,000+",
    stackTags: ["C#", "TypeScript", "C++", "Python", "Azure", "Rust", "Go"],
    gameTags: ["Xbox", "Game Pass", "DirectX"],
    roleFocusTags: ["backend", "cloud", "gaming", "AI", "productivity"],
    industryTags: ["cloud", "productivity", "enterprise", "gaming"],
    atsProviders: ["Workday"],
    notes: "Azure, Office 365, GitHub, Xbox, and Copilot AI.",
    activeHiring: true,
  },
  {
    name: "Netflix",
    slug: "netflix",
    websiteUrl: "https://www.netflix.com",
    careersUrl: "https://jobs.netflix.com",
    headquarters: "Los Gatos, CA",
    hiringRegions: ["US", "Global"],
    locations: ["Los Gatos, CA", "Los Angeles, CA", "New York, NY", "Remote"],
    remotePolicy: "REMOTE_FRIENDLY",
    companyCategory: "SOFTWARE",
    companySize: "10,000+",
    stackTags: ["Java", "Python", "Go", "React", "Kotlin", "Spinnaker", "Kafka"],
    gameTags: [],
    roleFocusTags: ["backend", "streaming", "ML", "infra"],
    industryTags: ["streaming", "entertainment", "gaming"],
    atsProviders: ["Greenhouse"],
    notes: "Freedom and responsibility culture. Top-of-market compensation.",
    activeHiring: true,
  },
  {
    name: "Stripe",
    slug: "stripe",
    websiteUrl: "https://www.stripe.com",
    careersUrl: "https://stripe.com/jobs",
    headquarters: "San Francisco, CA",
    hiringRegions: ["US", "Europe", "Remote"],
    locations: ["San Francisco, CA", "New York, NY", "Remote"],
    remotePolicy: "REMOTE_FRIENDLY",
    companyCategory: "SOFTWARE",
    companySize: "5,001–10,000",
    stackTags: ["Ruby", "Java", "Go", "TypeScript", "React", "Scala"],
    gameTags: [],
    roleFocusTags: ["backend", "payments", "infra", "developer tools"],
    industryTags: ["fintech", "payments", "developer tools"],
    atsProviders: ["Lever"],
    notes: "Payments infrastructure. High engineering bar, well-written job descriptions.",
    activeHiring: true,
  },
  {
    name: "Shopify",
    slug: "shopify",
    websiteUrl: "https://www.shopify.com",
    careersUrl: "https://www.shopify.com/careers",
    headquarters: "Ottawa, Canada",
    hiringRegions: ["US", "Canada", "Europe", "Remote"],
    locations: ["Ottawa, Canada", "Toronto, Canada", "New York, NY", "Remote"],
    remotePolicy: "REMOTE_FIRST",
    companyCategory: "SOFTWARE",
    companySize: "10,000+",
    stackTags: ["Ruby on Rails", "React", "TypeScript", "Go", "GraphQL", "Kubernetes"],
    gameTags: [],
    roleFocusTags: ["full stack", "backend", "payments", "mobile"],
    industryTags: ["e-commerce", "SaaS", "merchant tools"],
    atsProviders: ["Greenhouse"],
    notes: "Remote-first culture. Strong Ruby/Rails core with heavy TypeScript frontend.",
    activeHiring: true,
  },
  {
    name: "Airbnb",
    slug: "airbnb",
    websiteUrl: "https://www.airbnb.com",
    careersUrl: "https://careers.airbnb.com",
    headquarters: "San Francisco, CA",
    hiringRegions: ["US", "Remote"],
    locations: ["San Francisco, CA", "Seattle, WA", "Remote"],
    remotePolicy: "REMOTE_FRIENDLY",
    companyCategory: "SOFTWARE",
    companySize: "5,001–10,000",
    stackTags: ["React", "TypeScript", "Java", "Python", "Swift", "Kotlin", "Airflow"],
    gameTags: [],
    roleFocusTags: ["frontend", "backend", "mobile", "data"],
    industryTags: ["travel", "marketplace", "hospitality"],
    atsProviders: ["Greenhouse"],
    notes: "Remote-friendly culture. Strong React/TypeScript frontend culture.",
    activeHiring: true,
  },
  {
    name: "Figma",
    slug: "figma",
    websiteUrl: "https://www.figma.com",
    careersUrl: "https://www.figma.com/careers",
    headquarters: "San Francisco, CA",
    hiringRegions: ["US", "Remote"],
    locations: ["San Francisco, CA", "New York, NY", "Remote"],
    remotePolicy: "FLEXIBLE",
    companyCategory: "SOFTWARE",
    companySize: "1,001–2,000",
    stackTags: ["C++", "TypeScript", "React", "Rust", "WebAssembly", "gRPC"],
    gameTags: [],
    roleFocusTags: ["frontend", "backend", "graphics", "developer tools"],
    industryTags: ["design tools", "collaboration", "SaaS"],
    atsProviders: ["Greenhouse"],
    notes: "Design collaboration platform. Heavy C++ and WebAssembly core engine.",
    activeHiring: true,
  },
  {
    name: "Datadog",
    slug: "datadog",
    websiteUrl: "https://www.datadoghq.com",
    careersUrl: "https://www.datadoghq.com/careers",
    headquarters: "New York, NY",
    hiringRegions: ["US", "Europe", "Remote"],
    locations: ["New York, NY", "Boston, MA", "Remote"],
    remotePolicy: "REMOTE_FRIENDLY",
    companyCategory: "SOFTWARE",
    companySize: "5,001–10,000",
    stackTags: ["Go", "Python", "Java", "Rust", "TypeScript", "Kubernetes", "Kafka"],
    gameTags: [],
    roleFocusTags: ["backend", "SRE", "DevOps", "observability"],
    industryTags: ["monitoring", "observability", "cloud", "DevOps"],
    atsProviders: ["Greenhouse"],
    notes: "Observability platform. Strong Go/Python engineering culture.",
    activeHiring: true,
  },
  {
    name: "Cloudflare",
    slug: "cloudflare",
    websiteUrl: "https://www.cloudflare.com",
    careersUrl: "https://www.cloudflare.com/careers",
    headquarters: "San Francisco, CA",
    hiringRegions: ["US", "Europe", "Remote"],
    locations: ["San Francisco, CA", "Austin, TX", "London, UK", "Remote"],
    remotePolicy: "REMOTE_FRIENDLY",
    companyCategory: "SOFTWARE",
    companySize: "2,001–5,000",
    stackTags: ["Rust", "Go", "C++", "TypeScript", "Lua", "Workers"],
    gameTags: [],
    roleFocusTags: ["backend", "networking", "security", "edge computing"],
    industryTags: ["CDN", "security", "networking", "edge"],
    atsProviders: ["Greenhouse"],
    notes: "Global CDN and security platform. Deep systems engineering (Rust, C++).",
    activeHiring: true,
  },
  {
    name: "Twilio",
    slug: "twilio",
    websiteUrl: "https://www.twilio.com",
    careersUrl: "https://www.twilio.com/en-us/company/jobs",
    headquarters: "San Francisco, CA",
    hiringRegions: ["US", "Remote"],
    locations: ["San Francisco, CA", "Remote"],
    remotePolicy: "REMOTE_FIRST",
    companyCategory: "SOFTWARE",
    companySize: "5,001–10,000",
    stackTags: ["Java", "Python", "Go", "Node.js", "TypeScript", "Kubernetes", "AWS"],
    gameTags: [],
    roleFocusTags: ["backend", "platform", "API", "voice"],
    industryTags: ["CPaaS", "communications", "developer tools"],
    atsProviders: ["Greenhouse"],
    notes: "Communications APIs. Remote-first engineering culture.",
    activeHiring: true,
  },
  {
    name: "HashiCorp",
    slug: "hashicorp",
    websiteUrl: "https://www.hashicorp.com",
    careersUrl: "https://www.hashicorp.com/jobs",
    headquarters: "San Francisco, CA",
    hiringRegions: ["US", "Remote"],
    locations: ["Remote"],
    remotePolicy: "REMOTE_FIRST",
    companyCategory: "SOFTWARE",
    companySize: "1,001–2,000",
    stackTags: ["Go", "HCL", "Terraform", "Vault", "Consul", "Kubernetes"],
    gameTags: [],
    roleFocusTags: ["backend", "DevOps", "cloud infra"],
    industryTags: ["infrastructure", "DevOps", "cloud"],
    atsProviders: ["Greenhouse"],
    notes: "Makers of Terraform, Vault, Consul, Nomad. Fully remote.",
    activeHiring: true,
  },
  {
    name: "Vercel",
    slug: "vercel",
    websiteUrl: "https://www.vercel.com",
    careersUrl: "https://vercel.com/careers",
    headquarters: "San Francisco, CA",
    hiringRegions: ["US", "Europe", "Remote"],
    locations: ["Remote"],
    remotePolicy: "REMOTE_FIRST",
    companyCategory: "SOFTWARE",
    companySize: "201–500",
    stackTags: ["TypeScript", "React", "Next.js", "Node.js", "Rust", "Go"],
    gameTags: [],
    roleFocusTags: ["frontend", "developer experience", "edge"],
    industryTags: ["developer tools", "hosting", "frontend"],
    atsProviders: ["Ashby"],
    notes: "Creator of Next.js. Fully remote. Strong DX and frontend culture.",
    activeHiring: true,
  },
  {
    name: "Linear",
    slug: "linear",
    websiteUrl: "https://www.linear.app",
    careersUrl: "https://linear.app/careers",
    headquarters: "San Francisco, CA",
    hiringRegions: ["US", "Europe", "Remote"],
    locations: ["Remote"],
    remotePolicy: "REMOTE_FIRST",
    companyCategory: "SOFTWARE",
    companySize: "1–50",
    stackTags: ["TypeScript", "React", "Node.js", "GraphQL", "Electron"],
    gameTags: [],
    roleFocusTags: ["frontend", "backend", "product"],
    industryTags: ["project management", "developer tools", "SaaS"],
    atsProviders: ["Ashby"],
    notes: "Project management tool known for polish. Fully remote, small elite team.",
    activeHiring: true,
  },
  {
    name: "Notion",
    slug: "notion",
    websiteUrl: "https://www.notion.so",
    careersUrl: "https://www.notion.so/careers",
    headquarters: "San Francisco, CA",
    hiringRegions: ["US", "Remote"],
    locations: ["San Francisco, CA", "New York, NY", "Remote"],
    remotePolicy: "REMOTE_FRIENDLY",
    companyCategory: "SOFTWARE",
    companySize: "501–1,000",
    stackTags: ["TypeScript", "React", "Node.js", "Python", "Go"],
    gameTags: [],
    roleFocusTags: ["frontend", "backend", "mobile", "AI"],
    industryTags: ["productivity", "SaaS", "collaboration"],
    atsProviders: ["Greenhouse"],
    notes: "Productivity and collaboration workspace. Strong TypeScript/React culture.",
    activeHiring: true,
  },
  {
    name: "Anthropic",
    slug: "anthropic",
    websiteUrl: "https://www.anthropic.com",
    careersUrl: "https://www.anthropic.com/careers",
    headquarters: "San Francisco, CA",
    hiringRegions: ["US", "Remote"],
    locations: ["San Francisco, CA", "Remote"],
    remotePolicy: "FLEXIBLE",
    companyCategory: "SOFTWARE",
    companySize: "201–500",
    stackTags: ["Python", "PyTorch", "JAX", "Rust", "TypeScript", "React"],
    gameTags: [],
    roleFocusTags: ["ML research", "AI safety", "backend", "infra"],
    industryTags: ["AI", "safety", "LLMs", "research"],
    atsProviders: ["Greenhouse"],
    notes: "AI safety company building Claude. Research-heavy hiring.",
    activeHiring: true,
  },
  {
    name: "OpenAI",
    slug: "openai",
    websiteUrl: "https://www.openai.com",
    careersUrl: "https://openai.com/careers",
    headquarters: "San Francisco, CA",
    hiringRegions: ["US", "Remote"],
    locations: ["San Francisco, CA", "Remote"],
    remotePolicy: "FLEXIBLE",
    companyCategory: "SOFTWARE",
    companySize: "501–1,000",
    stackTags: ["Python", "PyTorch", "Kubernetes", "TypeScript", "React"],
    gameTags: [],
    roleFocusTags: ["ML research", "backend", "infra", "product"],
    industryTags: ["AI", "LLMs", "research"],
    atsProviders: ["Greenhouse"],
    notes: "Maker of ChatGPT and GPT-4. Highly competitive hiring.",
    activeHiring: true,
  },

  // ── US Gaming Studios ────────────────────────────────────────────
  {
    name: "Riot Games",
    slug: "riot-games",
    websiteUrl: "https://www.riotgames.com",
    careersUrl: "https://www.riotgames.com/en/work-with-us",
    headquarters: "Los Angeles, CA",
    hiringRegions: ["US", "Europe", "Asia"],
    locations: ["Los Angeles, CA", "Remote"],
    remotePolicy: "FLEXIBLE",
    companyCategory: "GAMING",
    companySize: "5,001–10,000",
    stackTags: ["C++", "Java", "Go", "Python", "TypeScript", "Unreal Engine"],
    gameTags: ["League of Legends", "VALORANT", "Wild Rift", "Teamfight Tactics"],
    roleFocusTags: ["game programming", "live ops", "ML", "tools"],
    industryTags: ["AAA games", "esports", "MOBA", "FPS"],
    atsProviders: ["Greenhouse"],
    notes: "Maker of League of Legends and VALORANT. Strong technical culture.",
    activeHiring: true,
  },
  {
    name: "Valve",
    slug: "valve",
    websiteUrl: "https://www.valvesoftware.com",
    careersUrl: "https://www.valvesoftware.com/en/jobs",
    headquarters: "Bellevue, WA",
    hiringRegions: ["US"],
    locations: ["Bellevue, WA"],
    remotePolicy: "ONSITE",
    companyCategory: "GAMING",
    companySize: "201–500",
    stackTags: ["C++", "Vulkan", "Source 2", "Python", "Go"],
    gameTags: ["Steam", "Half-Life", "Dota 2", "Counter-Strike", "VR"],
    roleFocusTags: ["game programming", "graphics", "tools"],
    industryTags: ["AAA games", "platform", "VR"],
    atsProviders: [],
    notes: "Flat structure, no formal management. Highly selective. Apply directly via website.",
    activeHiring: true,
  },
  {
    name: "Blizzard Entertainment",
    slug: "blizzard",
    websiteUrl: "https://www.blizzard.com",
    careersUrl: "https://careers.blizzard.com",
    headquarters: "Irvine, CA",
    hiringRegions: ["US", "Europe"],
    locations: ["Irvine, CA", "Austin, TX", "Albany, NY"],
    remotePolicy: "HYBRID",
    companyCategory: "GAMING",
    companySize: "5,001–10,000",
    stackTags: ["C++", "Python", "Unreal Engine", "JavaScript"],
    gameTags: ["World of Warcraft", "Overwatch", "Diablo", "Hearthstone"],
    roleFocusTags: ["game programming", "game design", "live ops"],
    industryTags: ["AAA games", "MMORPG", "FPS"],
    atsProviders: ["Workday"],
    notes: "Part of Microsoft / Activision Blizzard. Strong game design culture.",
    activeHiring: true,
  },
  {
    name: "Bungie",
    slug: "bungie",
    websiteUrl: "https://www.bungie.net",
    careersUrl: "https://careers.bungie.com",
    headquarters: "Bellevue, WA",
    hiringRegions: ["US", "Remote"],
    locations: ["Bellevue, WA", "Remote"],
    remotePolicy: "REMOTE_FRIENDLY",
    companyCategory: "GAMING",
    companySize: "1,001–2,000",
    stackTags: ["C++", "Unreal Engine", "Python", "JavaScript"],
    gameTags: ["Destiny", "Marathon"],
    roleFocusTags: ["game programming", "engine", "gameplay"],
    industryTags: ["AAA games", "FPS", "live service"],
    atsProviders: ["Greenhouse"],
    notes: "Maker of Destiny. Remote-friendly. Sony subsidiary.",
    activeHiring: true,
  },
  {
    name: "Insomniac Games",
    slug: "insomniac-games",
    websiteUrl: "https://insomniac.games",
    careersUrl: "https://insomniac.games/careers",
    headquarters: "Burbank, CA",
    hiringRegions: ["US"],
    locations: ["Burbank, CA"],
    remotePolicy: "ONSITE",
    companyCategory: "GAMING",
    companySize: "1,001–2,000",
    stackTags: ["C++", "C#", "Unreal Engine", "custom engines"],
    gameTags: ["Spider-Man", "Ratchet & Clank", "Marvel's Wolverine"],
    roleFocusTags: ["game programming", "graphics", "gameplay"],
    industryTags: ["AAA games", "PlayStation", "action"],
    atsProviders: ["Greenhouse"],
    notes: "Sony PlayStation Studios. Makers of Spider-Man.",
    activeHiring: true,
  },
  {
    name: "CD Projekt Red",
    slug: "cdprojektred",
    websiteUrl: "https://www.cdprojektred.com",
    careersUrl: "https://careers.cdprojektred.com",
    headquarters: "Warsaw, Poland",
    hiringRegions: ["Europe", "US", "Remote"],
    locations: ["Warsaw, Poland", "Boston, MA"],
    remotePolicy: "FLEXIBLE",
    companyCategory: "GAMING",
    companySize: "1,001–2,000",
    stackTags: ["C++", "REDengine", "Unreal Engine 5", "Blueprints"],
    gameTags: ["Cyberpunk 2077", "The Witcher", "Witcher 4"],
    roleFocusTags: ["game programming", "graphics", "game design"],
    industryTags: ["AAA games", "RPG"],
    atsProviders: ["Greenhouse"],
    notes: "Makers of The Witcher and Cyberpunk 2077. Boston studio expanding.",
    activeHiring: true,
  },
  {
    name: "2K Games",
    slug: "2k-games",
    websiteUrl: "https://2k.com",
    careersUrl: "https://2k.com/careers",
    headquarters: "San Mateo, CA",
    hiringRegions: ["US", "UK", "Australia"],
    locations: ["San Mateo, CA", "Novato, CA", "Las Vegas, NV"],
    remotePolicy: "HYBRID",
    companyCategory: "GAMING",
    companySize: "1,001–5,000",
    stackTags: ["C++", "Unreal Engine", "C#", "Python"],
    gameTags: ["Borderlands", "BioShock", "NBA 2K", "Civilization"],
    roleFocusTags: ["game programming", "game design", "tools"],
    industryTags: ["AAA games", "sports games", "FPS"],
    atsProviders: ["Workday"],
    notes: "Take-Two Interactive subsidiary. Multiple studios across genres.",
    activeHiring: true,
  },
  {
    name: "Ubisoft",
    slug: "ubisoft",
    websiteUrl: "https://www.ubisoft.com",
    careersUrl: "https://www.ubisoft.com/en-us/company/careers",
    headquarters: "Montreuil, France",
    hiringRegions: ["Europe", "US", "Canada"],
    locations: ["Montreal, Canada", "Toronto, Canada", "San Francisco, CA", "Paris, France"],
    remotePolicy: "HYBRID",
    companyCategory: "GAMING",
    companySize: "10,000+",
    stackTags: ["C++", "C#", "Unity", "Snowdrop", "Python"],
    gameTags: ["Assassin's Creed", "Far Cry", "Rainbow Six", "Watch Dogs"],
    roleFocusTags: ["game programming", "game design", "tools", "online"],
    industryTags: ["AAA games", "open world", "action"],
    atsProviders: ["Workday"],
    notes: "French AAA publisher. Multiple studios globally.",
    activeHiring: true,
  },
  {
    name: "Supercell",
    slug: "supercell",
    websiteUrl: "https://supercell.com",
    careersUrl: "https://supercell.com/en/careers",
    headquarters: "Helsinki, Finland",
    hiringRegions: ["Europe", "US", "Remote"],
    locations: ["Helsinki, Finland", "San Francisco, CA", "Seoul, South Korea"],
    remotePolicy: "FLEXIBLE",
    companyCategory: "GAMING",
    companySize: "201–500",
    stackTags: ["C++", "Java", "C#", "Unity"],
    gameTags: ["Clash of Clans", "Brawl Stars", "Clash Royale"],
    roleFocusTags: ["game programming", "game design", "live ops"],
    industryTags: ["mobile games", "F2P", "strategy"],
    atsProviders: [],
    notes: "Independent mobile game studio. Small cell-based teams.",
    activeHiring: true,
  },
  {
    name: "King",
    slug: "king",
    websiteUrl: "https://www.king.com",
    careersUrl: "https://careers.king.com",
    headquarters: "Stockholm, Sweden",
    hiringRegions: ["Europe", "US", "Remote"],
    locations: ["Stockholm, Sweden", "London, UK", "Barcelona, Spain", "San Francisco, CA"],
    remotePolicy: "FLEXIBLE",
    companyCategory: "GAMING",
    companySize: "2,001–5,000",
    stackTags: ["Java", "C++", "C#", "Unity", "Python"],
    gameTags: ["Candy Crush", "Farm Heroes", "Bubble Witch"],
    roleFocusTags: ["mobile games", "backend", "data"],
    industryTags: ["mobile games", "casual games", "F2P"],
    atsProviders: ["Workday"],
    notes: "Activision Blizzard subsidiary. Mobile casual games.",
    activeHiring: true,
  },

  // ── Remote-first / Distributed ───────────────────────────────────
  {
    name: "GitLab",
    slug: "gitlab",
    websiteUrl: "https://www.gitlab.com",
    careersUrl: "https://about.gitlab.com/jobs",
    headquarters: "San Francisco, CA",
    hiringRegions: ["Global", "Remote"],
    locations: ["Remote"],
    remotePolicy: "REMOTE_FIRST",
    companyCategory: "SOFTWARE",
    companySize: "2,001–5,000",
    stackTags: ["Ruby on Rails", "Go", "Vue.js", "TypeScript", "Python", "Kubernetes"],
    gameTags: [],
    roleFocusTags: ["backend", "frontend", "DevOps", "platform"],
    industryTags: ["DevOps", "CI/CD", "version control"],
    atsProviders: ["Greenhouse"],
    notes: "Fully remote DevOps platform. Public handbook. Strong async culture.",
    activeHiring: true,
  },
  {
    name: "GitHub",
    slug: "github",
    websiteUrl: "https://www.github.com",
    careersUrl: "https://github.com/about/careers",
    headquarters: "San Francisco, CA",
    hiringRegions: ["US", "Remote"],
    locations: ["Remote"],
    remotePolicy: "REMOTE_FIRST",
    companyCategory: "SOFTWARE",
    companySize: "1,001–5,000",
    stackTags: ["Ruby", "Go", "TypeScript", "React", "C#", "Kubernetes"],
    gameTags: [],
    roleFocusTags: ["backend", "frontend", "developer tools", "AI"],
    industryTags: ["developer tools", "version control", "CI/CD"],
    atsProviders: ["Greenhouse"],
    notes: "Microsoft subsidiary. Developer platform. Remote-first culture.",
    activeHiring: true,
  },
  {
    name: "Automattic",
    slug: "automattic",
    websiteUrl: "https://automattic.com",
    careersUrl: "https://automattic.com/work-with-us",
    headquarters: "San Francisco, CA",
    hiringRegions: ["Global", "Remote"],
    locations: ["Remote"],
    remotePolicy: "REMOTE_FIRST",
    companyCategory: "SOFTWARE",
    companySize: "2,001–5,000",
    stackTags: ["PHP", "JavaScript", "TypeScript", "React", "Node.js", "WordPress"],
    gameTags: [],
    roleFocusTags: ["full stack", "backend", "mobile"],
    industryTags: ["blogging", "CMS", "e-commerce"],
    atsProviders: ["Greenhouse"],
    notes: "Makers of WordPress.com, WooCommerce. Fully distributed globally.",
    activeHiring: true,
  },
  {
    name: "Basecamp (37signals)",
    slug: "37signals",
    websiteUrl: "https://37signals.com",
    careersUrl: "https://37signals.com/jobs",
    headquarters: "Chicago, IL",
    hiringRegions: ["US", "Remote"],
    locations: ["Remote"],
    remotePolicy: "REMOTE_FIRST",
    companyCategory: "SOFTWARE",
    companySize: "51–200",
    stackTags: ["Ruby on Rails", "TypeScript", "React", "Hotwire", "iOS"],
    gameTags: [],
    roleFocusTags: ["full stack", "mobile", "product"],
    industryTags: ["project management", "SaaS", "productivity"],
    atsProviders: [],
    notes: "Makers of Basecamp and HEY. Remote-first, calm company culture.",
    activeHiring: false,
  },
  {
    name: "Buffer",
    slug: "buffer",
    websiteUrl: "https://buffer.com",
    careersUrl: "https://buffer.com/journey",
    headquarters: "San Francisco, CA",
    hiringRegions: ["Global", "Remote"],
    locations: ["Remote"],
    remotePolicy: "REMOTE_FIRST",
    companyCategory: "SOFTWARE",
    companySize: "51–200",
    stackTags: ["Node.js", "React", "TypeScript", "GraphQL", "Python"],
    gameTags: [],
    roleFocusTags: ["full stack", "backend", "data"],
    industryTags: ["social media", "SaaS", "marketing tools"],
    atsProviders: [],
    notes: "Transparent salary and equity culture. Fully distributed.",
    activeHiring: true,
  },

  // ── International ────────────────────────────────────────────────
  {
    name: "Spotify",
    slug: "spotify",
    websiteUrl: "https://www.spotify.com",
    careersUrl: "https://www.spotify.com/us/jobs",
    headquarters: "Stockholm, Sweden",
    hiringRegions: ["Europe", "US", "Remote"],
    locations: ["Stockholm, Sweden", "New York, NY", "London, UK", "Boston, MA", "Remote"],
    remotePolicy: "FLEXIBLE",
    companyCategory: "SOFTWARE",
    companySize: "10,000+",
    stackTags: ["Java", "Python", "Go", "TypeScript", "React", "Kafka", "Backstage"],
    gameTags: [],
    roleFocusTags: ["backend", "ML", "data", "mobile"],
    industryTags: ["music streaming", "podcasts", "audio"],
    atsProviders: ["Greenhouse"],
    notes: "Creator of Backstage developer portal. Strong Python/Java backend.",
    activeHiring: true,
  },
  {
    name: "DICE (EA)",
    slug: "dice-ea",
    websiteUrl: "https://www.dice.se",
    careersUrl: "https://www.ea.com/careers",
    headquarters: "Stockholm, Sweden",
    hiringRegions: ["Europe", "US"],
    locations: ["Stockholm, Sweden", "Los Angeles, CA"],
    remotePolicy: "HYBRID",
    companyCategory: "GAMING",
    companySize: "501–1,000",
    stackTags: ["C++", "Frostbite", "Python"],
    gameTags: ["Battlefield", "Star Wars Battlefront"],
    roleFocusTags: ["game programming", "graphics", "physics"],
    industryTags: ["AAA games", "FPS", "multiplayer"],
    atsProviders: ["Workday"],
    notes: "EA subsidiary. Makers of Battlefield. Frostbite engine team.",
    activeHiring: true,
  },
  {
    name: "Mojang Studios",
    slug: "mojang",
    websiteUrl: "https://www.minecraft.net",
    careersUrl: "https://careers.microsoft.com",
    headquarters: "Stockholm, Sweden",
    hiringRegions: ["Europe", "US", "Remote"],
    locations: ["Stockholm, Sweden", "Redmond, WA", "Remote"],
    remotePolicy: "FLEXIBLE",
    companyCategory: "GAMING",
    companySize: "501–1,000",
    stackTags: ["Java", "C++", "C#", "Bedrock", "Python"],
    gameTags: ["Minecraft", "Minecraft Dungeons"],
    roleFocusTags: ["game programming", "platform", "tools"],
    industryTags: ["sandbox games", "education", "Java games"],
    atsProviders: ["Workday"],
    notes: "Microsoft subsidiary. Minecraft team. Hybrid culture.",
    activeHiring: true,
  },
  {
    name: "Wargaming",
    slug: "wargaming",
    websiteUrl: "https://www.wargaming.com",
    careersUrl: "https://jobs.wargaming.com",
    headquarters: "Nicosia, Cyprus",
    hiringRegions: ["Europe", "US", "Asia"],
    locations: ["Nicosia, Cyprus", "Prague, Czech Republic", "Serbia", "Remote"],
    remotePolicy: "FLEXIBLE",
    companyCategory: "GAMING",
    companySize: "5,001–10,000",
    stackTags: ["C++", "Python", "BigWorld", "Go"],
    gameTags: ["World of Tanks", "World of Warships", "World of Warplanes"],
    roleFocusTags: ["game programming", "backend", "live ops"],
    industryTags: ["MMO", "simulation games", "free-to-play"],
    atsProviders: ["Workday"],
    notes: "Large MMO publisher. Multiple global studios.",
    activeHiring: true,
  },
  {
    name: "Ustwo",
    slug: "ustwo",
    websiteUrl: "https://www.ustwo.com",
    careersUrl: "https://www.ustwo.com/careers",
    headquarters: "London, UK",
    hiringRegions: ["Europe", "US", "Remote"],
    locations: ["London, UK", "Malmö, Sweden", "New York, NY"],
    remotePolicy: "FLEXIBLE",
    companyCategory: "BOTH",
    companySize: "201–500",
    stackTags: ["Swift", "Kotlin", "React", "Unity", "C++"],
    gameTags: ["Monument Valley", "Alba"],
    roleFocusTags: ["mobile", "game programming", "UX"],
    industryTags: ["indie games", "apps", "design"],
    atsProviders: [],
    notes: "Indie game and mobile app studio. Makers of Monument Valley.",
    activeHiring: true,
  },
  {
    name: "Grab",
    slug: "grab",
    websiteUrl: "https://www.grab.com",
    careersUrl: "https://grab.careers",
    headquarters: "Singapore",
    hiringRegions: ["Southeast Asia", "Remote"],
    locations: ["Singapore", "Bangalore, India", "Kuala Lumpur, Malaysia"],
    remotePolicy: "HYBRID",
    companyCategory: "SOFTWARE",
    companySize: "5,001–10,000",
    stackTags: ["Go", "Java", "Python", "Kotlin", "Swift", "Kafka", "Kubernetes"],
    gameTags: [],
    roleFocusTags: ["backend", "mobile", "data", "ML"],
    industryTags: ["super app", "fintech", "food delivery", "ride-hailing"],
    atsProviders: ["Workday"],
    notes: "Southeast Asia super app. Strong Go/Java backend engineering.",
    activeHiring: true,
  },
  {
    name: "Wise",
    slug: "wise",
    websiteUrl: "https://www.wise.com",
    careersUrl: "https://wise.jobs",
    headquarters: "London, UK",
    hiringRegions: ["Europe", "US", "Remote"],
    locations: ["London, UK", "Tallinn, Estonia", "Austin, TX", "Remote"],
    remotePolicy: "FLEXIBLE",
    companyCategory: "SOFTWARE",
    companySize: "2,001–5,000",
    stackTags: ["Java", "Python", "TypeScript", "React", "Kotlin", "Swift"],
    gameTags: [],
    roleFocusTags: ["backend", "fintech", "mobile", "compliance"],
    industryTags: ["fintech", "money transfer", "banking"],
    atsProviders: ["Greenhouse"],
    notes: "International money transfer. Transparent pricing culture.",
    activeHiring: true,
  },
  {
    name: "Delivery Hero",
    slug: "delivery-hero",
    websiteUrl: "https://www.deliveryhero.com",
    careersUrl: "https://careers.deliveryhero.com",
    headquarters: "Berlin, Germany",
    hiringRegions: ["Europe", "Asia", "Remote"],
    locations: ["Berlin, Germany", "Remote"],
    remotePolicy: "FLEXIBLE",
    companyCategory: "SOFTWARE",
    companySize: "10,000+",
    stackTags: ["Go", "Java", "Kotlin", "Python", "TypeScript", "React", "Kubernetes"],
    gameTags: [],
    roleFocusTags: ["backend", "mobile", "data", "platform"],
    industryTags: ["food delivery", "marketplace", "logistics"],
    atsProviders: ["Greenhouse"],
    notes: "Global food delivery platform operating in 50+ countries.",
    activeHiring: true,
  },
  {
    name: "King (Sweden)",
    slug: "king-sweden",
    websiteUrl: "https://www.king.com",
    careersUrl: "https://careers.king.com",
    headquarters: "Stockholm, Sweden",
    hiringRegions: ["Europe", "Remote"],
    locations: ["Stockholm, Sweden", "London, UK", "Barcelona, Spain"],
    remotePolicy: "FLEXIBLE",
    companyCategory: "GAMING",
    companySize: "2,001–5,000",
    stackTags: ["Java", "C++", "Unity", "Python"],
    gameTags: ["Candy Crush Saga", "Farm Heroes Saga"],
    roleFocusTags: ["mobile games", "backend", "data science"],
    industryTags: ["mobile games", "casual games"],
    atsProviders: ["Workday"],
    notes: "Activision Blizzard subsidiary. European mobile gaming giant.",
    activeHiring: true,
  },
  {
    name: "Atlassian",
    slug: "atlassian",
    websiteUrl: "https://www.atlassian.com",
    careersUrl: "https://www.atlassian.com/company/careers",
    headquarters: "Sydney, Australia",
    hiringRegions: ["US", "Europe", "Australia", "Remote"],
    locations: ["Sydney, Australia", "San Francisco, CA", "New York, NY", "Austin, TX", "Remote"],
    remotePolicy: "REMOTE_FIRST",
    companyCategory: "SOFTWARE",
    companySize: "10,000+",
    stackTags: ["Java", "Python", "TypeScript", "React", "Kotlin", "AWS"],
    gameTags: [],
    roleFocusTags: ["backend", "frontend", "platform", "DevOps"],
    industryTags: ["developer tools", "project management", "collaboration"],
    atsProviders: ["Workday"],
    notes: "Jira, Confluence, Trello, Bitbucket. Remote-first TEAM Anywhere policy.",
    activeHiring: true,
  },
  {
    name: "Canva",
    slug: "canva",
    websiteUrl: "https://www.canva.com",
    careersUrl: "https://www.canva.com/careers",
    headquarters: "Sydney, Australia",
    hiringRegions: ["Australia", "US", "Europe", "Remote"],
    locations: ["Sydney, Australia", "San Francisco, CA", "Beijing, China", "Remote"],
    remotePolicy: "FLEXIBLE",
    companyCategory: "SOFTWARE",
    companySize: "2,001–5,000",
    stackTags: ["Java", "TypeScript", "React", "Go", "Python", "gRPC"],
    gameTags: [],
    roleFocusTags: ["frontend", "backend", "mobile", "data"],
    industryTags: ["design tools", "SaaS", "productivity"],
    atsProviders: ["Greenhouse"],
    notes: "Design platform with strong engineering culture. Fast growth.",
    activeHiring: true,
  },
];

async function main() {
  console.log(`Seeding ${companies.length} companies (upsert)...`);
  let upserted = 0;

  for (const company of companies) {
    const data = {
      name: company.name,
      websiteUrl: company.websiteUrl ?? null,
      careersUrl: company.careersUrl ?? null,
      headquarters: company.headquarters ?? null,
      hiringRegions: s(company.hiringRegions),
      locations: s(company.locations),
      remotePolicy: company.remotePolicy as any,
      companyCategory: company.companyCategory as any,
      companySize: company.companySize ?? null,
      stackTags: s(company.stackTags),
      gameTags: s(company.gameTags),
      roleFocusTags: s(company.roleFocusTags),
      industryTags: s(company.industryTags),
      hiringSignals: s([]),
      atsProviders: s(company.atsProviders),
      emailPatterns: s([]),
      notes: company.notes ?? null,
      outreachTips: null,
      linkedinUrl: null,
      activeHiring: company.activeHiring,
    };

    await prisma.company.upsert({
      where: { slug: company.slug },
      update: data,
      create: { ...data, slug: company.slug },
    });

    upserted++;
    if (upserted % 10 === 0) process.stdout.write(`  ${upserted}/${companies.length}\n`);
  }

  console.log(`\nDone — ${upserted} companies upserted.`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
